spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: create
    show-sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      transport.protocol: smtp
      mail.smtp:
        auth: true
        starttls.enable: true
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
oauth:
  jwt.key: test
  client:
    id: nsai
    secret: nsai
  token.validity: 86400
captcha:
  enable: true
  url: https://www.google.com/recaptcha/api/siteverify?secret={secret}&response={response}
  secret:
  site:
registration:
  mail:
    enable: false
    url: http://localhost:8081/register/activate?token=